=== AutoscanForJava/net.sf.aislib-aislib/src/main/resources/pl/aislib/fm/dtds/messages_0_2.dtd
<!--
  -
  - "-//AIS.PL//DTD Messages Description 0.2//EN"
  - "http://www.ais.pl/dtds/messages_0_2.dtd"
  -
  - Warlock, 06.03.2002
  -
  - Changes since base 0.2 version
  - 2003.07.18 wswiatek: added 'type' attribute for 'message' element
  -                      added 'lang' attribute for 'messages' and 'message' element as default language
  - 2002.11.15 andy: allowed more than one 'content' element, added 'lang' attribute to the 'content' element
  - 2002.08.30 pikus: add 'message-group' and 'message-ref' elements
  -->

<!ELEMENT messages (message+,message-group*)>

<!ATTLIST messages
          lang NMTOKEN #IMPLIED>

<!ELEMENT message (key, content+)>

<!ATTLIST message 
          code  CDATA #REQUIRED
          type CDATA #IMPLIED
          lang NMTOKEN #IMPLIED>

<!ELEMENT key (#PCDATA)>

<!ELEMENT content (#PCDATA)>

<!ATTLIST content
          lang NMTOKEN #IMPLIED>

<!ELEMENT message-group (message-ref+)>

<!ATTLIST message-group
          code  CDATA #REQUIRED>

<!ELEMENT message-ref EMPTY>

<!ATTLIST message-ref
          ref-code CDATA #REQUIRED>

=== AutoscanForJava/net.sf.aislib-aislib/src/test/resources/pl/aislib/test/fm/forms/messages_messages.xml
<!DOCTYPE messages PUBLIC "-//AIS.PL//DTD Messages Description 0.2//EN"
                          "http://www.ais.pl/dtds/messages_0_2.dtd">

<messages>
  <message code="0">
    <key>dummy</key>
    <content></content>
  </message>

  <message code="1">
    <key>field_{3}_empty</key>
    <content>field no. {4} ({2}) is empty.</content>
  </message>

  <message code="2">
    <key>field_{3}_invalid</key>
    <content>field no. {4} ({2}) is invalid.</content>
  </message>

  <message code="3">
    <key>field_{3}_invalid</key>
    <content>field no. {4} ({2}) with suffix {5} is invalid.</content>
  </message>

  <message code="4">
    <key>Aislib version {custom:version}: field_{entity:name}_empty_{entity:name}.</key>
    <content>field no. {entity:name} ({1}) is empty. Required property is set to {validator:required}. Minimum length is set to {validator:minimumLength}. Generic name is {entity:genericName}.</content>
  </message>

  <message code="5">
    <key>rule_{entity:name}_invalid</key>
    <content>Rule {entity:name} is invalid. Value of object1 is {rule:object1:value}.</content>
  </message>

  <message code="6">
    <key>key</key>
    <content>{entity:dynamicCount,choice,1#one|1&lt;many {entity:dynamicCount}}</content>
  </message>

</messages>

=== AutoscanForJava/net.sf.aislib-aislib/src/test/pl/aislib/test/fm/forms/messages_messages.xml
<!DOCTYPE messages PUBLIC "-//AIS.PL//DTD Messages Description 0.2//EN"
                          "http://www.ais.pl/dtds/messages_0_2.dtd">

<messages>
  <message code="0">
    <key>dummy</key>
    <content></content>
  </message>

  <message code="1">
    <key>field_{3}_empty</key>
    <content>field no. {4} ({2}) is empty.</content>
  </message>

  <message code="2">
    <key>field_{3}_invalid</key>
    <content>field no. {4} ({2}) is invalid.</content>
  </message>

  <message code="3">
    <key>field_{3}_invalid</key>
    <content>field no. {4} ({2}) with suffix {5} is invalid.</content>
  </message>
</messages>

=== AutoscanForJava/net.sf.aislib-aislib/src/test/pl/aislib/test/fm/forms/messages_fields.xml
<!DOCTYPE messages PUBLIC "-//AIS.PL//DTD Messages Description 0.2//EN"
                          "http://www.ais.pl/dtds/messages_0_2.dtd">

<messages>
  <message code="1">
    <key>field_001_empty</key>
    <content>field_001 is empty.</content>
  </message>

  <message code="2">
    <key>field_001_invalid</key>
    <content>Invalid field_001.</content>
  </message>

  <message code="3">
    <key>field_002_invalid</key>
    <content>Invalid field_002.</content>
  </message>

  <message code="4">
    <key>field_002_invalid</key>
    <content>Invalid field_002.</content>
  </message>

  <message code="5">
    <key>field_002_invalid</key>
    <content>Invalid field_002.</content>
  </message>
</messages>
