=== AutoscanForJava/net.sf.aislib-aislib/src/resources/pl/aislib/fm/dtds/forms_0_4.dtd
<!--
  -
  - "-//AIS.PL//DTD Forms Description 0.4//EN"
  - "http://www.ais.pl/dtds/forms_0_4.dtd"
  -
  - wswiatek, last modified: 23.09.2002
  -
  - Warlock, last modified: 07.03.2002
  -
  - base 0.2 version created on 06.03.2002
  -
  - changes since base 0.2 version:
  - 2002.03.07: added 'property' child for element 'rule'
  - 2002.09.23: added many new features
  -->

<!ELEMENT forms (form+)>

<!ELEMENT form (fields,rules?)>

<!ATTLIST form 
          name          CDATA #REQUIRED>

<!ELEMENT fields (field+)>

<!ELEMENT field (builder?, validation*)>

<!ATTLIST field 
          class         CDATA #REQUIRED
          name          CDATA #REQUIRED
          dynamic       CDATA 'false'>

<!ELEMENT builder (property*, builder-mapping+)>

<!ATTLIST builder
          class         CDATA #REQUIRED>

<!ELEMENT builder-mapping EMPTY>

<!ATTLIST builder-mapping
          field-param CDATA #REQUIRED
          field-name  CDATA #REQUIRED>

<!ELEMENT validation (property*)>

<!ATTLIST validation 
          msg-code      CDATA #REQUIRED>

<!ELEMENT rules (rule+)>

<!ELEMENT rule (property*, mapping+)>

<!ATTLIST rule 
          class     CDATA #REQUIRED
          msg-code  CDATA #REQUIRED
          name      CDATA #REQUIRED>

<!ELEMENT property EMPTY>

<!ATTLIST property 
          name   CDATA #REQUIRED
          value  CDATA #REQUIRED>

<!ELEMENT mapping EMPTY>

<!ATTLIST mapping 
          field-name  CDATA #REQUIRED
          rule-param  CDATA #REQUIRED>

=== AutoscanForJava/net.sf.aislib-aislib/src/test/pl/aislib/test/fm/forms/forms_rules.xml
<!DOCTYPE forms PUBLIC "-//AIS.PL//DTD Forms Description 0.4//EN"
                       "http://www.ais.pl/dtds/forms_0_4.dtd"
[
  <!ENTITY fv "pl.aislib.util.validators.">
  <!ENTITY fr "pl.aislib.util.rules.">
]>

<forms>
  <form name="form_date_range_001">
    <fields>
      <field name="field_001" class="&fv;DateValidator">
        <validation msg-code="1">
          <property name="required" value="true"/>
        </validation>
      </field>
      <field name="field_002" class="&fv;DateValidator">
        <validation msg-code="2">
          <property name="required" value="true"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_001" class="&fr;DateRangeRule" msg-code="3">
      	<mapping rule-param="from_date" field-name="field_001"/>
      	<mapping rule-param="to_date" field-name="field_002"/>
      </rule>
    </rules>
  </form>

  <form name="form_date_range_002">
    <fields>
      <field name="field_001_" class="&fv;DateValidator" dynamic="true">
        <validation msg-code="1">
          <property name="required" value="true"/>
        </validation>
      </field>
      <field name="field_002_" class="&fv;DateValidator" dynamic="true">
        <validation msg-code="2">
          <property name="required" value="true"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_001_" class="&fr;DateRangeRule" msg-code="3">
      	<mapping rule-param="from_date" field-name="field_001_"/>
      	<mapping rule-param="to_date" field-name="field_002_"/>
      </rule>
    </rules>
  </form>
  
  <form name="form_equality_001">
    <fields>
      <field name="field_001" class="&fv;StringValidator">
        <validation msg-code="5">
          <property name="required" value="true"/>
        </validation>
      </field>
      <field name="field_002" class="&fv;StringValidator">
        <validation msg-code="5">
          <property name="required" value="true"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_001" class="&fr;EqualityRule" msg-code="6">
        <mapping rule-param="object1" field-name="field_001"/>
        <mapping rule-param="object2" field-name="field_002"/>
      </rule>
    </rules>
  </form>

  <form name="form_equality_002">
    <fields>
      <field name="field_001" class="&fv;StringValidator">
        <validation msg-code="5">
          <property name="required" value="false"/>
        </validation>
      </field>
      <field name="field_002" class="&fv;StringValidator">
        <validation msg-code="5">
          <property name="required" value="false"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_001" class="&fr;EqualityRule" msg-code="6">
        <mapping rule-param="object1" field-name="field_001"/>
        <mapping rule-param="object2" field-name="field_002"/>
      </rule>
    </rules>
  </form>

  <form name="form_equality_003">
    <fields>
      <field name="field_001" class="&fv;StringValidator">
        <validation msg-code="5">
          <property name="required" value="true"/>
        </validation>
      </field>
      <field name="field_002" class="&fv;StringValidator">
        <validation msg-code="5">
          <property name="required" value="true"/>
        </validation>
      </field>
      <field name="check_fields" class="&fv;StringValidator">
        <validation msg-code="5">
          <property name="required" value="false"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_001" class="&fr;EqualityRule" msg-code="6">
        <property name="checkCondition" value="true"/>
        <property name="checkConditionValue" value="y"/>
        <mapping rule-param="object1" field-name="field_001"/>
        <mapping rule-param="object2" field-name="field_002"/>
        <mapping rule-param="check" field-name="check_fields"/>
      </rule>
    </rules>
  </form>

  <form name="form_equality_004">
    <fields>
      <field name="field_001" class="&fv;StringValidator">
        <validation msg-code="5">
          <property name="required" value="false"/>
        </validation>
      </field>
      <field name="field_002" class="&fv;StringValidator">
        <validation msg-code="5">
          <property name="required" value="false"/>
        </validation>
      </field>
      <field name="check_fields" class="&fv;StringValidator">
        <validation msg-code="5">
          <property name="required" value="false"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_001" class="&fr;EqualityRule" msg-code="6">
        <property name="checkCondition" value="true"/>
        <property name="checkConditionValue" value="y"/>
        <mapping rule-param="object1" field-name="field_001"/>
        <mapping rule-param="object2" field-name="field_002"/>
        <mapping rule-param="check" field-name="check_fields"/>
      </rule>
    </rules>
  </form>

  <form name="form_equality_005">
    <fields>
      <field name="field_001" class="&fv;IntegerValidator">
        <validation msg-code="5">
          <property name="required" value="true"/>
        </validation>
      </field>
      <field name="field_002" class="&fv;IntegerValidator">
        <validation msg-code="5">
          <property name="required" value="true"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_001" class="&fr;EqualityRule" msg-code="6">
        <mapping rule-param="object1" field-name="field_001"/>
        <mapping rule-param="object2" field-name="field_002"/>
      </rule>
    </rules>
  </form>

  <form name="form_equality_006">
    <fields>
      <field name="field_001_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="7">
          <property name="required" value="true"/>
        </validation>
      </field>
      <field name="field_002_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="7">
          <property name="required" value="true"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_001_" class="&fr;EqualityRule" msg-code="8">
        <mapping rule-param="object1" field-name="field_001_"/>
        <mapping rule-param="object2" field-name="field_002_"/>
      </rule>
    </rules>
  </form>

  <form name="form_equality_007">
    <fields>
      <field name="field_001_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="7">
          <property name="required" value="true"/>
        </validation>
      </field>
      <field name="field_002_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="7">
          <property name="required" value="true"/>
        </validation>
      </field>
      <field name="check_fields_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="7">
          <property name="required" value="false"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_001_" class="&fr;EqualityRule" msg-code="8">
        <property name="checkCondition" value="true"/>
        <property name="checkConditionValue" value="y"/>
        <mapping rule-param="object1" field-name="field_001_"/>
        <mapping rule-param="object2" field-name="field_002_"/>
        <mapping rule-param="check" field-name="check_fields_"/>
      </rule>
    </rules>
  </form>
</forms>

=== AutoscanForJava/net.sf.aislib-aislib/src/test/resources/pl/aislib/test/fm/forms/properties_forms.xml
<!DOCTYPE forms PUBLIC "-//AIS.PL//DTD Forms Description 0.4//EN"
                       "http://www.ais.pl/dtds/forms_0_4.dtd"
[
  <!ENTITY root "pl.aislib.test.fm.forms">
  <!ENTITY fv   "pl.aislib.util.validators">
]>

<forms>
  <form name="form1">
    <fields>
      <field name="v1" class="&fv;.StringValidator">
         <validation msg-code="1"/>
      </field>
      <field name="result" class="&root;.SimpleValidator">
          <builder class="&root;.SimpleBuilder">
            <property name="property" value="Validator" />
            <builder-mapping field-name="v1" field-param="v1"/>
         </builder>
         <validation msg-code="1">
           <property name="property" value="Builder" />
        </validation>
      </field>
    </fields>
  </form>
</forms>

=== AutoscanForJava/net.sf.aislib-aislib/src/test/resources/pl/aislib/test/fm/forms/forms_messages.xml
<!DOCTYPE forms PUBLIC "-//AIS.PL//DTD Forms Description 0.4//EN"
                       "http://www.ais.pl/dtds/forms_0_4.dtd"
[
  <!ENTITY fv "pl.aislib.util.validators.">
  <!ENTITY fr "pl.aislib.util.rules.">
]>

<forms>
  <form name="form_messages_001">
    <fields>
      <field name="field_001_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="1">
          <property name="required" value="true"/>
        </validation>
      </field>
    </fields>
  </form>

  <form name="form_messages_002">
    <fields>
      <field name="field_002_" class="&fv;BigDecimalValidator" dynamic="true">
        <validation msg-code="2">
        </validation>
      </field>
    </fields>
  </form>

  <form name="form_messages_003">
    <fields>
      <field name="field_001_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="2">
          <property name="pattern" value="((\d\d-\d\d\d)|(\d\d\d\d\d))"/>
        </validation>
      </field>
      <field name="field_002_" class="&fv;DoubleValidator" dynamic="true">
        <validation msg-code="2">
          <property name="format" value="###,###,###,##0.##" />
        </validation>
      </field>
    </fields>
  </form>

  <form name="form_messages_004">
    <fields>
      <field name="check_001_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="2">
          <property name="required" value="false"/>
        </validation>
      </field>
      <field name="field_001_" class="&fv;IntegerValidator" dynamic="true">
        <validation msg-code="3">
          <property name="required" value="false"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_check_" class="&fr;CheckSingleFieldRule" msg-code="0">
        <property name="checkCondition" value="true"/>
        <property name="checkConditionValue" value="1"/>
        <mapping rule-param="check" field-name="check_001_"/>
        <mapping rule-param="field" field-name="field_001_"/>
      </rule>
    </rules>
  </form>

  <form name="form_messages_005">
    <fields>
      <field name="field_001" class="&fv;StringValidator">
        <validation msg-code="4">
          <property name="required" value="true"/>
          <property name="minimumLength" value="5"/>
        </validation>
      </field>
    </fields>
  </form>

  <form name="form_messages_006">
    <fields>
      <field name="field_001" class="&fv;StringValidator">
        <validation msg-code="4">
          <property name="required" value="true"/>
          <property name="minimumLength" value="5"/>
        </validation>
      </field>
      <field name="field_002" class="&fv;StringValidator">
        <validation msg-code="4">
          <property name="required" value="true"/>
          <property name="minimumLength" value="5"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_check" class="&fr;EqualityRule" msg-code="5">
        <mapping rule-param="object1" field-name="field_001"/>
        <mapping rule-param="object2" field-name="field_002"/>
      </rule>
    </rules>
  </form>

  <form name="form_messages_007">
    <fields>
      <field name="field_001_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="4">
          <property name="required" value="true"/>
          <property name="minimumLength" value="5"/>
        </validation>
      </field>
    </fields>
  </form>

  <form name="form_messages_008">
    <fields>
      <field name="field_001_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="4">
          <property name="required" value="true"/>
          <property name="minimumLength" value="5"/>
        </validation>
      </field>
      <field name="field_002_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="4">
          <property name="required" value="true"/>
          <property name="minimumLength" value="5"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_check_" class="&fr;EqualityRule" msg-code="5">
        <mapping rule-param="object1" field-name="field_001_"/>
        <mapping rule-param="object2" field-name="field_002_"/>
      </rule>
    </rules>
  </form>

  <form name="form_messages_009">
    <fields>
      <field name="field_001_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="4">
          <property name="required" value="true"/>
          <property name="minimumLength" value="5"/>
        </validation>
      </field>
      <field name="field_002_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="4">
          <property name="required" value="true"/>
          <property name="minimumLength" value="5"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_check_" class="&fr;EqualityRule" msg-code="6">
        <mapping rule-param="object1" field-name="field_001_"/>
        <mapping rule-param="object2" field-name="field_002_"/>
      </rule>
    </rules>
  </form>

</forms>

=== AutoscanForJava/net.sf.aislib-aislib/src/test/pl/aislib/test/fm/forms/forms_messages.xml
<!DOCTYPE forms PUBLIC "-//AIS.PL//DTD Forms Description 0.4//EN"
                       "http://www.ais.pl/dtds/forms_0_4.dtd"
[
  <!ENTITY fv "pl.aislib.util.validators.">
  <!ENTITY fr "pl.aislib.util.rules.">
]>

<forms>
  <form name="form_messages_001">
    <fields>
      <field name="field_001_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="1">
          <property name="required" value="true"/>
        </validation>
      </field>
    </fields>
  </form>
  
  <form name="form_messages_002">
    <fields>
      <field name="field_002_" class="&fv;BigDecimalValidator" dynamic="true">
        <validation msg-code="2">
        </validation>
      </field>
    </fields>
  </form>
  
  <form name="form_messages_003">
    <fields>
      <field name="field_001_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="2">
          <property name="regExp" value="((\d\d-\d\d\d)|(\d\d\d\d\d))"/>
        </validation>
      </field>
      <field name="field_002_" class="&fv;DoubleValidator" dynamic="true">
        <validation msg-code="2">
          <property name="format" value="###,###,###,##0.##" />
        </validation>
      </field>
    </fields>
  </form>
  
  <form name="form_messages_004">
    <fields>
      <field name="check_001_" class="&fv;StringValidator" dynamic="true">
        <validation msg-code="2">
          <property name="required" value="false"/>
        </validation>
      </field>
      <field name="field_001_" class="&fv;IntegerValidator" dynamic="true">
        <validation msg-code="3">
          <property name="required" value="false"/>
        </validation>
      </field>
    </fields>
    <rules>
      <rule name="rule_check" class="&fr;CheckSingleFieldRule" msg-code="0">
        <property name="checkCondition" value="true"/>
        <property name="checkConditionValue" value="1"/>
        <mapping rule-param="check" field-name="check_001_"/>
        <mapping rule-param="field" field-name="field_001_"/>
      </rule>
    </rules>
  </form>
</forms>
